[package]
name = "guessing-game"
version = "1.0.0"
authors = []

[addresses]
my_addrx = "7a59f367aca1633827bf7a57d9fe787a6fe7b6c340492ed8aad19ea565c3d23a"
std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
